<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\User;
use App\Models\Unit;
use App\Models\Company;
use App\Models\Brand;
use App\Models\Product;
use App\Models\ProductCategory;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'Test User',
            'email' => 'test@example.com',
        ]);
        $countries = [ 
            [ "name"=> "Afghanistan", "arabic_name"=> "أفغانستان", "iso2"=> "AF", "iso3"=> "AFG", "call_code"=> "+93", ], 
            [ "name"=> "Albania", "arabic_name"=> "ألبانيا", "iso2"=> "AL", "iso3"=> "ALB", "call_code"=> "+355", ], 
            [ "name"=> "Algeria", "arabic_name"=> "الجزائر", "iso2"=> "DZ", "iso3"=> "DZA", "call_code"=> "+213", ], 
            [ "name"=> "Andorra", "arabic_name"=> "أندورا", "iso2"=> "AD", "iso3"=> "AND", "call_code"=> "+376", ], 
            [ "name"=> "Angola", "arabic_name"=> "أنغولا", "iso2"=> "AO", "iso3"=> "AGO", "call_code"=> "+244", ], 
            [ "name"=> "Antigua and Barbuda", "arabic_name"=> "أنتيغوا وباربودا", "iso2"=> "AG", "iso3"=> "ATG", "call_code"=> "+1-268", ], 
            [ "name"=> "Argentina", "arabic_name"=> "الأرجنتين", "iso2"=> "AR", "iso3"=> "ARG", "call_code"=> "+54", ], 
            [ "name"=> "Armenia", "arabic_name"=> "أرمينيا", "iso2"=> "AM", "iso3"=> "ARM", "call_code"=> "+374", ], 
            [ "name"=> "Australia", "arabic_name"=> "أستراليا", "iso2"=> "AU", "iso3"=> "AUS", "call_code"=> "+61", ], 
            [ "name"=> "Austria", "arabic_name"=> "النمسا", "iso2"=> "AT", "iso3"=> "AUT", "call_code"=> "+43", ], 
            [ "name"=> "Azerbaijan", "arabic_name"=> "أذربيجان", "iso2"=> "AZ", "iso3"=> "AZE", "call_code"=> "+994", ], 
            [ "name"=> "Bahamas", "arabic_name"=> "الباهاما", "iso2"=> "BS", "iso3"=> "BHS", "call_code"=> "+1-242", ], 
            [ "name"=> "Bahrain", "arabic_name"=> "البحرين", "iso2"=> "BH", "iso3"=> "BHR", "call_code"=> "+973", ],
            [ "name"=> "Bangladesh", "arabic_name"=> "بنغلاديش", "iso2"=> "BD", "iso3"=> "BGD", "call_code"=> "+880", ], 
            [ "name"=> "Barbados", "arabic_name"=> "بربادوس", "iso2"=> "BB", "iso3"=> "BRB", "call_code"=> "+1-246", ], 
            [ "name"=> "Belarus", "arabic_name"=> "بيلاروسيا", "iso2"=> "BY", "iso3"=> "BLR", "call_code"=> "+375", ], 
            [ "name"=> "Belgium", "arabic_name"=> "بلجيكا", "iso2"=> "BE", "iso3"=> "BEL", "call_code"=> "+32", ], 
            [ "name"=> "Belize", "arabic_name"=> "بليز", "iso2"=> "BZ", "iso3"=> "BLZ", "call_code"=> "+501", ], 
            [ "name"=> "Benin", "arabic_name"=> "بنين", "iso2"=> "BJ", "iso3"=> "BEN", "call_code"=> "+229", ], 
            [ "name"=> "Bhutan", "arabic_name"=> "بوتان", "iso2"=> "BT", "iso3"=> "BTN", "call_code"=> "+975", ], 
            [ "name"=> "Bolivia", "arabic_name"=> "بوليفيا", "iso2"=> "BO", "iso3"=> "BOL", "call_code"=> "+591", ], 
            [ "name"=> "Bosnia and Herzegovina", "arabic_name"=> "البوسنة والهرسك", "iso2"=> "BA", "iso3"=> "BIH", "call_code"=> "+387", ], 
            [ "name"=> "Botswana", "arabic_name"=> "بوتسوانا", "iso2"=> "BW", "iso3"=> "BWA", "call_code"=> "+267", ], 
            [ "name"=> "Brazil", "arabic_name"=> "البرازيل", "iso2"=> "BR", "iso3"=> "BRA", "call_code"=> "+55", ], 
            [ "name"=> "Brunei", "arabic_name"=> "بروناي", "iso2"=> "BN", "iso3"=> "BRN", "call_code"=> "+673", ], 
            [ "name"=> "Bulgaria", "arabic_name"=> "بلغاريا", "iso2"=> "BG", "iso3"=> "BGR", "call_code"=> "+359", ], 
            [ "name"=> "Burkina Faso", "arabic_name"=> "بوركينا فاسو", "iso2"=> "BF", "iso3"=> "BFA", "call_code"=> "+226", ], 
            [ "name"=> "Burundi", "arabic_name"=> "بوروندي", "iso2"=> "BI", "iso3"=> "BDI", "call_code"=> "+257", ], 
            [ "name"=> "Cabo Verde", "arabic_name"=> "الرأس الأخضر", "iso2"=> "CV", "iso3"=> "CPV", "call_code"=> "+238", ], 
            [ "name"=> "Cambodia", "arabic_name"=> "كمبوديا", "iso2"=> "KH", "iso3"=> "KHM", "call_code"=> "+855", ], 
            [ "name"=> "Cameroon", "arabic_name"=> "الكاميرون", "iso2"=> "CM", "iso3"=> "CMR", "call_code"=> "+237", ], 
            [ "name"=> "Canada", "arabic_name"=> "كندا", "iso2"=> "CA", "iso3"=> "CAN", "call_code"=> "+1", ], 
            [ "name"=> "Central African Republic", "arabic_name"=> "جمهورية أفريقيا الوسطى", "iso2"=> "CF", "iso3"=> "CAF", "call_code"=> "+236", ], 
            [ "name"=> "Chad", "arabic_name"=> "تشاد", "iso2"=> "TD", "iso3"=> "TCD", "call_code"=> "+235", ], 
            [ "name"=> "Chile", "arabic_name"=> "تشيلي", "iso2"=> "CL", "iso3"=> "CHL", "call_code"=> "+56", ], 
            [ "name"=> "China", "arabic_name"=> "الصين", "iso2"=> "CN", "iso3"=> "CHN", "call_code"=> "+86", ], 
            [ "name"=> "Colombia", "arabic_name"=> "كولومبيا", "iso2"=> "CO", "iso3"=> "COL", "call_code"=> "+57", ], 
            [ "name"=> "Comoros", "arabic_name"=> "جزر القمر", "iso2"=> "KM", "iso3"=> "COM", "call_code"=> "+269", ], 
            [ "name"=> "Congo (Congo-Brazzaville)", "arabic_name"=> "الكونغو", "iso2"=> "CG", "iso3"=> "COG", "call_code"=> "+242", ], 
            [ "name"=> "Costa Rica", "arabic_name"=> "كوستاريكا", "iso2"=> "CR", "iso3"=> "CRI", "call_code"=> "+506", ], 
            [ "name"=> "Croatia", "arabic_name"=> "كرواتيا", "iso2"=> "HR", "iso3"=> "HRV", "call_code"=> "+385", ], 
            [ "name"=> "Cuba", "arabic_name"=> "كوبا", "iso2"=> "CU", "iso3"=> "CUB", "call_code"=> "+53", ], 
            [ "name"=> "Cyprus", "arabic_name"=> "قبرص", "iso2"=> "CY", "iso3"=> "CYP", "call_code"=> "+357", ], 
            [ "name"=> "Czechia (Czech Republic)", "arabic_name"=> "التشيك", "iso2"=> "CZ", "iso3"=> "CZE", "call_code"=> "+420", ], 
            [ "name"=> "Democratic Republic of the Congo", "arabic_name"=> "جمهورية الكونغو الديمقراطية", "iso2"=> "CD", "iso3"=> "COD", "call_code"=> "+243", ], 
            [ "name"=> "Denmark", "arabic_name"=> "الدنمارك", "iso2"=> "DK", "iso3"=> "DNK", "call_code"=> "+45", ], 
            [ "name"=> "Djibouti", "arabic_name"=> "جيبوتي", "iso2"=> "DJ", "iso3"=> "DJI", "call_code"=> "+253", ], 
            [ "name"=> "Dominica", "arabic_name"=> "دومينيكا", "iso2"=> "DM", "iso3"=> "DMA", "call_code"=> "+1-767", ], 
            [ "name"=> "Dominican Republic", "arabic_name"=> "جمهورية الدومينيكان", "iso2"=> "DO", "iso3"=> "DOM", "call_code"=> "+1-809", ], 
            [ "name"=> "Ecuador", "arabic_name"=> "الإكوادور", "iso2"=> "EC", "iso3"=> "ECU", "call_code"=> "+593", ], 
            [ "name"=> "Egypt", "arabic_name"=> "مصر", "iso2"=> "EG", "iso3"=> "EGY", "call_code"=> "+20", ], 
            [ "name"=> "El Salvador", "arabic_name"=> "السلفادور", "iso2"=> "SV", "iso3"=> "SLV", "call_code"=> "+503", ], 
            [ "name"=> "Equatorial Guinea", "arabic_name"=> "غينيا الاستوائية", "iso2"=> "GQ", "iso3"=> "GNQ", "call_code"=> "+240", ], 
            [ "name"=> "Eritrea", "arabic_name"=> "إريتريا", "iso2"=> "ER", "iso3"=> "ERI", "call_code"=> "+291", ], 
            [ "name"=> "Estonia", "arabic_name"=> "إستونيا", "iso2"=> "EE", "iso3"=> "EST", "call_code"=> "+372", ], 
            [ "name"=> "Eswatini (fmr. 'Swaziland')", "arabic_name"=> "إسواتيني", "iso2"=> "SZ", "iso3"=> "SWZ", "call_code"=> "+268", ], 
            [ "name"=> "Ethiopia", "arabic_name"=> "إثيوبيا", "iso2"=> "ET", "iso3"=> "ETH", "call_code"=> "+251", ], 
            [ "name"=> "Fiji", "arabic_name"=> "فيجي", "iso2"=> "FJ", "iso3"=> "FJI", "call_code"=> "+679", ], 
            [ "name"=> "Finland", "arabic_name"=> "فنلندا", "iso2"=> "FI", "iso3"=> "FIN", "call_code"=> "+358", ], 
            [ "name"=> "France", "arabic_name"=> "فرنسا", "iso2"=> "FR", "iso3"=> "FRA", "call_code"=> "+33", ], 
            [ "name"=> "Gabon", "arabic_name"=> "الغابون", "iso2"=> "GA", "iso3"=> "GAB", "call_code"=> "+241", ], 
            [ "name"=> "Gambia", "arabic_name"=> "غامبيا", "iso2"=> "GM", "iso3"=> "GMB", "call_code"=> "+220", ], 
            [ "name"=> "Georgia", "arabic_name"=> "جورجيا", "iso2"=> "GE", "iso3"=> "GEO", "call_code"=> "+995", ], 
            [ "name"=> "Germany", "arabic_name"=> "ألمانيا", "iso2"=> "DE", "iso3"=> "DEU", "call_code"=> "+49", ], 
            [ "name"=> "Ghana", "arabic_name"=> "غانا", "iso2"=> "GH", "iso3"=> "GHA", "call_code"=> "+233", ], 
            [ "name"=> "Greece", "arabic_name"=> "اليونان", "iso2"=> "GR", "iso3"=> "GRC", "call_code"=> "+30", ], 
            [ "name"=> "Grenada", "arabic_name"=> "غرينادا", "iso2"=> "GD", "iso3"=> "GRD", "call_code"=> "+1-473", ], 
            [ "name"=> "Guatemala", "arabic_name"=> "غواتيمالا", "iso2"=> "GT", "iso3"=> "GTM", "call_code"=> "+502", ], 
            [ "name"=> "Guinea", "arabic_name"=> "غينيا", "iso2"=> "GN", "iso3"=> "GIN", "call_code"=> "+224", ], 
            [ "name"=> "Guinea-Bissau", "arabic_name"=> "غينيا بيساو", "iso2"=> "GW", "iso3"=> "GNB", "call_code"=> "+245", ], 
            [ "name"=> "Guyana", "arabic_name"=> "غيانا", "iso2"=> "GY", "iso3"=> "GUY", "call_code"=> "+592", ], 
            [ "name"=> "Haiti", "arabic_name"=> "هايتي", "iso2"=> "HT", "iso3"=> "HTI", "call_code"=> "+509", ], 
            [ "name"=> "Honduras", "arabic_name"=> "هندوراس", "iso2"=> "HN", "iso3"=> "HND", "call_code"=> "+504", ], 
            [ "name"=> "Hungary", "arabic_name"=> "المجر", "iso2"=> "HU", "iso3"=> "HUN", "call_code"=> "+36", ], 
            [ "name"=> "Iceland", "arabic_name"=> "آيسلندا", "iso2"=> "IS", "iso3"=> "ISL", "call_code"=> "+354", ], 
            [ "name"=> "India", "arabic_name"=> "الهند", "iso2"=> "IN", "iso3"=> "IND", "call_code"=> "+91", ], 
            [ "name"=> "Indonesia", "arabic_name"=> "إندونيسيا", "iso2"=> "ID", "iso3"=> "IDN", "call_code"=> "+62", ], 
            [ "name"=> "Iran", "arabic_name"=> "إيران", "iso2"=> "IR", "iso3"=> "IRN", "call_code"=> "+98", ], 
            [ "name"=> "Iraq", "arabic_name"=> "العراق", "iso2"=> "IQ", "iso3"=> "IRQ", "call_code"=> "+964", ], 
            [ "name"=> "Ireland", "arabic_name"=> "أيرلندا", "iso2"=> "IE", "iso3"=> "IRL", "call_code"=> "+353", ], 
            [ "name"=> "Israel", "arabic_name"=> "إسرائيل", "iso2"=> "IL", "iso3"=> "ISR", "call_code"=> "+972", ], 
            [ "name"=> "Italy", "arabic_name"=> "إيطاليا", "iso2"=> "IT", "iso3"=> "ITA", "call_code"=> "+39", ], 
            [ "name"=> "Jamaica", "arabic_name"=> "جامايكا", "iso2"=> "JM", "iso3"=> "JAM", "call_code"=> "+1-876", ], 
            [ "name"=> "Japan", "arabic_name"=> "اليابان", "iso2"=> "JP", "iso3"=> "JPN", "call_code"=> "+81", ], 
            [ "name"=> "Jordan", "arabic_name"=> "الأردن", "iso2"=> "JO", "iso3"=> "JOR", "call_code"=> "+962", ], 
            [ "name"=> "Kazakhstan", "arabic_name"=> "كازاخستان", "iso2"=> "KZ", "iso3"=> "KAZ", "call_code"=> "+7", ], 
            [ "name"=> "Kenya", "arabic_name"=> "كينيا", "iso2"=> "KE", "iso3"=> "KEN", "call_code"=> "+254", ], 
            [ "name"=> "Kiribati", "arabic_name"=> "كيريباتي", "iso2"=> "KI", "iso3"=> "KIR", "call_code"=> "+686", ], 
            [ "name"=> "Kuwait", "arabic_name"=> "الكويت", "iso2"=> "KW", "iso3"=> "KWT", "call_code"=> "+965", ], 
            [ "name"=> "Kyrgyzstan", "arabic_name"=> "قيرغيزستان", "iso2"=> "KG", "iso3"=> "KGZ", "call_code"=> "+996", ], 
            [ "name"=> "Laos", "arabic_name"=> "لاوس", "iso2"=> "LA", "iso3"=> "LAO", "call_code"=> "+856", ], 
            [ "name"=> "Latvia", "arabic_name"=> "لاتفيا", "iso2"=> "LV", "iso3"=> "LVA", "call_code"=> "+371", ], 
            [ "name"=> "Lebanon", "arabic_name"=> "لبنان", "iso2"=> "LB", "iso3"=> "LBN", "call_code"=> "+961", ], 
            [ "name"=> "Lesotho", "arabic_name"=> "ليسوتو", "iso2"=> "LS", "iso3"=> "LSO", "call_code"=> "+266", ], 
            [ "name"=> "Liberia", "arabic_name"=> "ليبيريا", "iso2"=> "LR", "iso3"=> "LBR", "call_code"=> "+231", ], 
            [ "name"=> "Libya", "arabic_name"=> "ليبيا", "iso2"=> "LY", "iso3"=> "LBY", "call_code"=> "+218", ], 
            [ "name"=> "Liechtenstein", "arabic_name"=> "ليختنشتاين", "iso2"=> "LI", "iso3"=> "LIE", "call_code"=> "+423", ], 
            [ "name"=> "Lithuania", "arabic_name"=> "ليتوانيا", "iso2"=> "LT", "iso3"=> "LTU", "call_code"=> "+370", ], 
            [ "name"=> "Luxembourg", "arabic_name"=> "لوكسمبورغ", "iso2"=> "LU", "iso3"=> "LUX", "call_code"=> "+352", ], 
            [ "name"=> "Madagascar", "arabic_name"=> "مدغشقر", "iso2"=> "MG", "iso3"=> "MDG", "call_code"=> "+261", ], 
            [ "name"=> "Malawi", "arabic_name"=> "مالاوي", "iso2"=> "MW", "iso3"=> "MWI", "call_code"=> "+265", ], 
            [ "name"=> "Malaysia", "arabic_name"=> "ماليزيا", "iso2"=> "MY", "iso3"=> "MYS", "call_code"=> "+60", ], 
            [ "name"=> "Maldives", "arabic_name"=> "المالديف", "iso2"=> "MV", "iso3"=> "MDV", "call_code"=> "+960", ], 
            [ "name"=> "Mali", "arabic_name"=> "مالي", "iso2"=> "ML", "iso3"=> "MLI", "call_code"=> "+223", ], 
            [ "name"=> "Malta", "arabic_name"=> "مالطا", "iso2"=> "MT", "iso3"=> "MLT", "call_code"=> "+356", ], 
            [ "name"=> "Marshall Islands", "arabic_name"=> "جزر مارشال", "iso2"=> "MH", "iso3"=> "MHL", "call_code"=> "+692", ], 
            [ "name"=> "Mauritania", "arabic_name"=> "موريتانيا", "iso2"=> "MR", "iso3"=> "MRT", "call_code"=> "+222", ], 
            [ "name"=> "Mauritius", "arabic_name"=> "موريشيوس", "iso2"=> "MU", "iso3"=> "MUS", "call_code"=> "+230", ], 
            [ "name"=> "Mexico", "arabic_name"=> "المكسيك", "iso2"=> "MX", "iso3"=> "MEX", "call_code"=> "+52", ], 
            [ "name"=> "Micronesia", "arabic_name"=> "ميكرونيزيا", "iso2"=> "FM", "iso3"=> "FSM", "call_code"=> "+691", ], 
            [ "name"=> "Moldova", "arabic_name"=> "مولدوفا", "iso2"=> "MD", "iso3"=> "MDA", "call_code"=> "+373", ], 
            [ "name"=> "Monaco", "arabic_name"=> "موناكو", "iso2"=> "MC", "iso3"=> "MCO", "call_code"=> "+377", ], 
            [ "name"=> "Mongolia", "arabic_name"=> "منغوليا", "iso2"=> "MN", "iso3"=> "MNG", "call_code"=> "+976", ], 
            [ "name"=> "Montenegro", "arabic_name"=> "الجبل الأسود", "iso2"=> "ME", "iso3"=> "MNE", "call_code"=> "+382", ], 
            [ "name"=> "Morocco", "arabic_name"=> "المغرب", "iso2"=> "MA", "iso3"=> "MAR", "call_code"=> "+212", ], 
            [ "name"=> "Mozambique", "arabic_name"=> "موزمبيق", "iso2"=> "MZ", "iso3"=> "MOZ", "call_code"=> "+258", ], 
            [ "name"=> "Myanmar (formerly Burma)", "arabic_name"=> "ميانمار", "iso2"=> "MM", "iso3"=> "MMR", "call_code"=> "+95", ], 
            [ "name"=> "Namibia", "arabic_name"=> "ناميبيا", "iso2"=> "NA", "iso3"=> "NAM", "call_code"=> "+264", ], 
            [ "name"=> "Nauru", "arabic_name"=> "ناورو", "iso2"=> "NR", "iso3"=> "NRU", "call_code"=> "+674", ], 
            [ "name"=> "Nepal", "arabic_name"=> "نيبال", "iso2"=> "NP", "iso3"=> "NPL", "call_code"=> "+977", ], 
            [ "name"=> "Netherlands", "arabic_name"=> "هولندا", "iso2"=> "NL", "iso3"=> "NLD", "call_code"=> "+31", ], 
            [ "name"=> "New Zealand", "arabic_name"=> "نيوزيلندا", "iso2"=> "NZ", "iso3"=> "NZL", "call_code"=> "+64", ], 
            [ "name"=> "Nicaragua", "arabic_name"=> "نيكاراغوا", "iso2"=> "NI", "iso3"=> "NIC", "call_code"=> "+505", ], 
            [ "name"=> "Niger", "arabic_name"=> "النيجر", "iso2"=> "NE", "iso3"=> "NER", "call_code"=> "+227", ], 
            [ "name"=> "Nigeria", "arabic_name"=> "نيجيريا", "iso2"=> "NG", "iso3"=> "NGA", "call_code"=> "+234", ], 
            [ "name"=> "North Korea", "arabic_name"=> "كوريا الشمالية", "iso2"=> "KP", "iso3"=> "PRK", "call_code"=> "+850", ], 
            [ "name"=> "North Macedonia", "arabic_name"=> "مقدونيا الشمالية", "iso2"=> "MK", "iso3"=> "MKD", "call_code"=> "+389", ], 
            [ "name"=> "Norway", "arabic_name"=> "النرويج", "iso2"=> "NO", "iso3"=> "NOR", "call_code"=> "+47", ], 
            [ "name"=> "Oman", "arabic_name"=> "عمان", "iso2"=> "OM", "iso3"=> "OMN", "call_code"=> "+968", ], 
            [ "name"=> "Pakistan", "arabic_name"=> "باكستان", "iso2"=> "PK", "iso3"=> "PAK", "call_code"=> "+92", ], 
            [ "name"=> "Palau", "arabic_name"=> "بالاو", "iso2"=> "PW", "iso3"=> "PLW", "call_code"=> "+680", ], 
            [ "name"=> "Palestine State", "arabic_name"=> "فلسطين", "iso2"=> "PS", "iso3"=> "PSE", "call_code"=> "+970", ], 
            [ "name"=> "Panama", "arabic_name"=> "بنما", "iso2"=> "PA", "iso3"=> "PAN", "call_code"=> "+507", ], 
            [ "name"=> "Papua New Guinea", "arabic_name"=> "بابوا غينيا الجديدة", "iso2"=> "PG", "iso3"=> "PNG", "call_code"=> "+675", ], 
            [ "name"=> "Paraguay", "arabic_name"=> "باراغواي", "iso2"=> "PY", "iso3"=> "PRY", "call_code"=> "+595", ], 
            [ "name"=> "Peru", "arabic_name"=> "بيرو", "iso2"=> "PE", "iso3"=> "PER", "call_code"=> "+51", ], 
            [ "name"=> "Philippines", "arabic_name"=> "الفلبين", "iso2"=> "PH", "iso3"=> "PHL", "call_code"=> "+63", ], 
            [ "name"=> "Poland", "arabic_name"=> "بولندا", "iso2"=> "PL", "iso3"=> "POL", "call_code"=> "+48", ], 
            [ "name"=> "Portugal", "arabic_name"=> "البرتغال", "iso2"=> "PT", "iso3"=> "PRT", "call_code"=> "+351", ], 
            [ "name"=> "Qatar", "arabic_name"=> "قطر", "iso2"=> "QA", "iso3"=> "QAT", "call_code"=> "+974", ], 
            [ "name"=> "Romania", "arabic_name"=> "رومانيا", "iso2"=> "RO", "iso3"=> "ROU", "call_code"=> "+40", ], 
            [ "name"=> "Russia", "arabic_name"=> "روسيا", "iso2"=> "RU", "iso3"=> "RUS", "call_code"=> "+7", ], 
            [ "name"=> "Rwanda", "arabic_name"=> "رواندا", "iso2"=> "RW", "iso3"=> "RWA", "call_code"=> "+250", ], 
            [ "name"=> "Saint Kitts and Nevis", "arabic_name"=> "سانت كيتس ونيفيس", "iso2"=> "KN", "iso3"=> "KNA", "call_code"=> "+1-869", ], 
            [ "name"=> "Saint Lucia", "arabic_name"=> "سانت لوسيا", "iso2"=> "LC", "iso3"=> "LCA", "call_code"=> "+1-758", ], 
            [ "name"=> "Saint Vincent and the Grenadines", "arabic_name"=> "سانت فنسنت وجزر غرينادين", "iso2"=> "VC", "iso3"=> "VCT", "call_code"=> "+1-784", ], 
            [ "name"=> "Samoa", "arabic_name"=> "ساموا", "iso2"=> "WS", "iso3"=> "WSM", "call_code"=> "+685", ], 
            [ "name"=> "San Marino", "arabic_name"=> "سان مارينو", "iso2"=> "SM", "iso3"=> "SMR", "call_code"=> "+378", ], 
            [ "name"=> "Sao Tome and Principe", "arabic_name"=> "ساو تومي وبرينسيبي", "iso2"=> "ST", "iso3"=> "STP", "call_code"=> "+239", ], 
            [ "name"=> "Saudi Arabia", "arabic_name"=> "المملكة العربية السعودية", "iso2"=> "SA", "iso3"=> "SAU", "call_code"=> "+966", ], 
            [ "name"=> "Senegal", "arabic_name"=> "السنغال", "iso2"=> "SN", "iso3"=> "SEN", "call_code"=> "+221", ], 
            [ "name"=> "Serbia", "arabic_name"=> "صربيا", "iso2"=> "RS", "iso3"=> "SRB", "call_code"=> "+381", ], 
            [ "name"=> "Seychelles", "arabic_name"=> "سيشيل", "iso2"=> "SC", "iso3"=> "SYC", "call_code"=> "+248", ], 
            [ "name"=> "Sierra Leone", "arabic_name"=> "سيراليون", "iso2"=> "SL", "iso3"=> "SLE", "call_code"=> "+232", ], 
            [ "name"=> "Singapore", "arabic_name"=> "سنغافورة", "iso2"=> "SG", "iso3"=> "SGP", "call_code"=> "+65", ], 
            [ "name"=> "Slovakia", "arabic_name"=> "سلوفاكيا", "iso2"=> "SK", "iso3"=> "SVK", "call_code"=> "+421", ], 
            [ "name"=> "Slovenia", "arabic_name"=> "سلوفينيا", "iso2"=> "SI", "iso3"=> "SVN", "call_code"=> "+386", ], 
            [ "name"=> "Solomon Islands", "arabic_name"=> "جزر سليمان", "iso2"=> "SB", "iso3"=> "SLB", "call_code"=> "+677", ], 
            [ "name"=> "Somalia", "arabic_name"=> "الصومال", "iso2"=> "SO", "iso3"=> "SOM", "call_code"=> "+252", ], 
            [ "name"=> "South Africa", "arabic_name"=> "جنوب أفريقيا", "iso2"=> "ZA", "iso3"=> "ZAF", "call_code"=> "+27", ], 
            [ "name"=> "South Korea", "arabic_name"=> "كوريا الجنوبية", "iso2"=> "KR", "iso3"=> "KOR", "call_code"=> "+82", ], 
            [ "name"=> "South Sudan", "arabic_name"=> "جنوب السودان", "iso2"=> "SS", "iso3"=> "SSD", "call_code"=> "+211", ], 
            [ "name"=> "Spain", "arabic_name"=> "إسبانيا", "iso2"=> "ES", "iso3"=> "ESP", "call_code"=> "+34", ], 
            [ "name"=> "Sri Lanka", "arabic_name"=> "سريلانكا", "iso2"=> "LK", "iso3"=> "LKA", "call_code"=> "+94", ], 
            [ "name"=> "Sudan", "arabic_name"=> "السودان", "iso2"=> "SD", "iso3"=> "SDN", "call_code"=> "+249", ], 
            [ "name"=> "Suriname", "arabic_name"=> "سورينام", "iso2"=> "SR", "iso3"=> "SUR", "call_code"=> "+597", ], 
            [ "name"=> "Sweden", "arabic_name"=> "السويد", "iso2"=> "SE", "iso3"=> "SWE", "call_code"=> "+46", ], 
            [ "name"=> "Switzerland", "arabic_name"=> "سويسرا", "iso2"=> "CH", "iso3"=> "CHE", "call_code"=> "+41", ], 
            [ "name"=> "Syria", "arabic_name"=> "سوريا", "iso2"=> "SY", "iso3"=> "SYR", "call_code"=> "+963", ], 
            [ "name"=> "Tajikistan", "arabic_name"=> "طاجيكستان", "iso2"=> "TJ", "iso3"=> "TJK", "call_code"=> "+992", ], 
            [ "name"=> "Tanzania", "arabic_name"=> "تنزانيا", "iso2"=> "TZ", "iso3"=> "TZA", "call_code"=> "+255", ], 
            [ "name"=> "Thailand", "arabic_name"=> "تايلاند", "iso2"=> "TH", "iso3"=> "THA", "call_code"=> "+66", ], 
            [ "name"=> "Timor-Leste", "arabic_name"=> "تيمور الشرقية", "iso2"=> "TL", "iso3"=> "TLS", "call_code"=> "+670", ], 
            [ "name"=> "Togo", "arabic_name"=> "توغو", "iso2"=> "TG", "iso3"=> "TGO", "call_code"=> "+228", ], 
            [ "name"=> "Tonga", "arabic_name"=> "تونغا", "iso2"=> "TO", "iso3"=> "TON", "call_code"=> "+676", ], 
            [ "name"=> "Trinidad and Tobago", "arabic_name"=> "ترينيداد وتوباغو", "iso2"=> "TT", "iso3"=> "TTO", "call_code"=> "+1-868", ], 
            [ "name"=> "Tunisia", "arabic_name"=> "تونس", "iso2"=> "TN", "iso3"=> "TUN", "call_code"=> "+216", ], 
            [ "name"=> "Turkey", "arabic_name"=> "تركيا", "iso2"=> "TR", "iso3"=> "TUR", "call_code"=> "+90", ], 
            [ "name"=> "Turkmenistan", "arabic_name"=> "تركمانستان", "iso2"=> "TM", "iso3"=> "TKM", "call_code"=> "+993", ], 
            [ "name"=> "Tuvalu", "arabic_name"=> "توفالو", "iso2"=> "TV", "iso3"=> "TUV", "call_code"=> "+688", ], 
            [ "name"=> "Uganda", "arabic_name"=> "أوغندا", "iso2"=> "UG", "iso3"=> "UGA", "call_code"=> "+256", ], 
            [ "name"=> "Ukraine", "arabic_name"=> "أوكرانيا", "iso2"=> "UA", "iso3"=> "UKR", "call_code"=> "+380", ], 
            [ "name"=> "United Arab Emirates", "arabic_name"=> "الإمارات العربية المتحدة", "iso2"=> "AE", "iso3"=> "ARE", "call_code"=> "+971", ], 
            [ "name"=> "United Kingdom", "arabic_name"=> "المملكة المتحدة", "iso2"=> "GB", "iso3"=> "GBR", "call_code"=> "+44", ], 
            [ "name"=> "United States of America", "arabic_name"=> "الولايات المتحدة الأمريكية", "iso2"=> "US", "iso3"=> "USA", "call_code"=> "+1", ], 
            [ "name"=> "Uruguay", "arabic_name"=> "أوروغواي", "iso2"=> "UY", "iso3"=> "URY", "call_code"=> "+598", ], 
            [ "name"=> "Uzbekistan", "arabic_name"=> "أوزبكستان", "iso2"=> "UZ", "iso3"=> "UZB", "call_code"=> "+998", ], 
            [ "name"=> "Vanuatu", "arabic_name"=> "فانواتو", "iso2"=> "VU", "iso3"=> "VUT", "call_code"=> "+678", ], 
            [ "name"=> "Vatican City", "arabic_name"=> "مدينة الفاتيكان", "iso2"=> "VA", "iso3"=> "VAT", "call_code"=> "+379", ], 
            [ "name"=> "Venezuela", "arabic_name"=> "فنزويلا", "iso2"=> "VE", "iso3"=> "VEN", "call_code"=> "+58", ], 
            [ "name"=> "Vietnam", "arabic_name"=> "فيتنام", "iso2"=> "VN", "iso3"=> "VNM", "call_code"=> "+84", ], 
            [ "name"=> "Yemen", "arabic_name"=> "اليمن", "iso2"=> "YE", "iso3"=> "YEM", "call_code"=> "+967", ], 
            [ "name"=> "Zambia", "arabic_name"=> "زامبيا", "iso2"=> "ZM", "iso3"=> "ZMB", "call_code"=> "+260", ], 
            [ "name"=> "Zimbabwe", "arabic_name"=> "زيمبابوي", "iso2"=> "ZW", "iso3"=> "ZWE", "call_code"=> "+263", ]
            
        ] ;
        Country::insert($countries);

        Unit::insert([
          [
              'name' => 'Piece',
              'description' => 'Individual pieces of items',
              'short_name' => 'pc',
              'created_at' => Carbon::now(),
              'updated_at' => Carbon::now(),
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'name' => 'Kilogram',
              'description' => 'Measurement unit for weight',
              'short_name' => 'kg',
              'created_at' => Carbon::now(),
              'updated_at' => Carbon::now(),
              'created_by' => 2,
              'updated_by' => 2,
          ],
          [
              'name' => 'Meter',
              'description' => 'Measurement unit for length',
              'short_name' => 'm',
              'created_at' => Carbon::now(),
              'updated_at' => Carbon::now(),
              'created_by' => 3,
              'updated_by' => 3,
          ],
          [
              'name' => 'Liter',
              'description' => 'Measurement unit for volume',
              'short_name' => 'L',
              'created_at' => Carbon::now(),
              'updated_at' => Carbon::now(),
              'created_by' => 4,
              'updated_by' => 4,
          ],
          [
              'name' => 'Box',
              'description' => 'Packaged in boxes',
              'short_name' => 'bx',
              'created_at' => Carbon::now(),
              'updated_at' => Carbon::now(),
              'created_by' => 5,
              'updated_by' => 5,
          ],
      ]);
        Company::insert([
          [
              'name' => 'Stylish Threads',
              'address' => '123 Fashion Avenue, New York, NY',
              'company_size' => '500-1000',
              'phone_number' => '1234567890',
              'incorporation_date' => '2010-05-15',
              'industry' => 'Clothing',
              'website' => 'https://stylishthreads.com',
              'created_at' => now(),
              'updated_at' => now(),
              'created_by' => 1,
              'updated_by' => 1,
          ],
          [
              'name' => 'Elegant Attire',
              'address' => '456 Couture Boulevard, Paris, France',
              'company_size' => '200-500',
              'phone_number' => '0987654321',
              'incorporation_date' => '2015-03-20',
              'industry' => 'Clothing',
              'website' => 'https://elegantattire.com',
              'created_at' => now(),
              'updated_at' => now(),
              'created_by' => 2,
              'updated_by' => 2,
          ],
          [
              'name' => 'Urban Wear',
              'address' => '789 Trendy Street, London, UK',
              'company_size' => '100-200',
              'phone_number' => '1122334455',
              'incorporation_date' => '2018-07-10',
              'industry' => 'Clothing',
              'website' => 'https://urbanwear.com',
              'created_at' => now(),
              'updated_at' => now(),
              'created_by' => 3,
              'updated_by' => 3,
          ],
          [
              'name' => 'Classic Chic',
              'address' => '321 Vintage Road, Milan, Italy',
              'company_size' => '50-100',
              'phone_number' => '5566778899',
              'incorporation_date' => '2012-09-25',
              'industry' => 'Clothing',
              'website' => 'https://classicchic.com',
              'created_at' => now(),
              'updated_at' => now(),
              'created_by' => 4,
              'updated_by' => 4,
          ],
          [
              'name' => 'Eco Fashion',
              'address' => '654 Greenway, San Francisco, CA',
              'company_size' => '20-50',
              'phone_number' => '9988776655',
              'incorporation_date' => '2016-01-30',
              'industry' => 'Clothing',
              'website' => 'https://ecofashion.com',
              'created_at' => now(),
              'updated_at' => now(),
              'created_by' => 5,
              'updated_by' => 5,
          ],
      ]);

      ProductCategory::insert([
        [
            'name' => 'Men’s Formal Wear',
            'brief' => 'Suits, shirts, and ties for men',
            'parent' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'created_by' => 1,
            'updated_by' => 1,
        ],
        [
            'name' => 'Women’s Casual Wear',
            'brief' => 'T-shirts, jeans, and skirts for women',
            'parent' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'created_by' => 2,
            'updated_by' => 2,
        ],
        [
            'name' => 'Kids’ Sportswear',
            'brief' => 'Sports clothing for children',
            'parent' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'created_by' => 3,
            'updated_by' => 3,
        ],
        [
            'name' => 'Accessories',
            'brief' => 'Bags and shoes',
            'parent' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'created_by' => 4,
            'updated_by' => 4,
        ],
        [
            'name' => 'Sportswear',
            'brief' => 'Yoga and running apparel',
            'parent' => null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            'created_by' => 5,
            'updated_by' => 5,
        ],
    ]);

    Brand::insert([
      [
          'name' => 'Nike',
          'description' => 'Global sportswear brand known for its athletic shoes, apparel, and equipment.',
          'brand_logo' => 'nike_logo.png',
          'country_origin' => 'USA',
          'website' => 'https://www.nike.com',
          'company_id' => 1,
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
          'created_by' => 1,
          'updated_by' => 1,
      ],
      [
          'name' => 'Adidas',
          'description' => 'International brand offering a range of sportswear and accessories.',
          'brand_logo' => 'adidas_logo.png',
          'country_origin' => 'Germany',
          'website' => 'https://www.adidas.com',
          'company_id' => 2,
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
          'created_by' => 2,
          'updated_by' => 2,
      ],
      [
          'name' => 'Zara',
          'description' => 'Fashion retailer known for its trendy clothing and accessories for men, women, and kids.',
          'brand_logo' => 'zara_logo.png',
          'country_origin' => 'Spain',
          'website' => 'https://www.zara.com',
          'company_id' => 3,
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
          'created_by' => 3,
          'updated_by' => 3,
      ],
      [
          'name' => 'H&M',
          'description' => 'Retail brand offering a variety of fashion-forward clothing at affordable prices.',
          'brand_logo' => 'hm_logo.png',
          'country_origin' => 'Sweden',
          'website' => 'https://www.hm.com',
          'company_id' => 4,
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
          'created_by' => 4,
          'updated_by' => 4,
      ],
      [
          'name' => 'Uniqlo',
          'description' => 'Brand known for its high-quality basics and casual wear for all ages.',
          'brand_logo' => 'uniqlo_logo.png',
          'country_origin' => 'Japan',
          'website' => 'https://www.uniqlo.com',
          'company_id' => 5,
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
          'created_by' => 5,
          'updated_by' => 5,
      ],
  ]);

  Product::insert([
    [
        'name' => 'Classic Shirt',
        'description' => 'A stylish classic shirt',
        'barcode' => '1234567890123',
        'price' => 49.99,
        'category' => 1,
        'unit' => 1,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'created_by' => 1,
        'updated_by' => 1,
    ],
    [
        'name' => 'Denim Jeans',
        'description' => 'Comfortable and durable jeans',
        'barcode' => '1234567890124',
        'price' => 79.99,
        'category' => 2,
        'unit' => 1,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'created_by' => 2,
        'updated_by' => 2,
    ],
    [
        'name' => 'Sports Jacket',
        'description' => 'Lightweight sports jacket',
        'barcode' => '1234567890125',
        'price' => 99.99,
        'category' => 3,
        'unit' => 1,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'created_by' => 3,
        'updated_by' => 3,
    ],
    [
        'name' => 'Running Shoes',
        'description' => 'High-performance running shoes',
        'barcode' => '1234567890126',
        'price' => 129.99,
        'category' => 4,
        'unit' => 1,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'created_by' => 4,
        'updated_by' => 4,
    ],
    [
        'name' => 'Summer Dress',
        'description' => 'Light and breezy summer dress',
        'barcode' => '1234567890127',
        'price' => 59.99,
        'category' => 5,
        'unit' => 1,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'created_by' => 5,
        'updated_by' => 5,
    ],
]);


    


    }
}
