<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable  
 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('name', 100)->nullable(false);
            $table->string('arabic_name', 100)->nullable(false);
            $table->string('iso2', 2)->nullable(false);
            $table->string('iso3', 3)->nullable(false);
            $table->string('call_code', 10)->nullable(false);

            $table->engine('InnoDB');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}


/*
INSERT INTO `countries` (`name`, `arabic_name`, `iso2`, `iso3`, `call_code`) VALUES
('Afghanistan', 'أفغانستان', 'AF', 'AFG', '+93'),
('Albania', 'ألبانيا', 'AL', 'ALB', '+355'),
('Algeria', 'الجزائر', 'DZ', 'DZA', '+213'),
('Andorra', 'أندورا', 'AD', 'AND', '+376'),
('Angola', 'أنغولا', 'AO', 'AGO', '+244'),
('Antigua and Barbuda', 'أنتيغوا وباربودا', 'AG', 'ATG', '+1-268'),
('Argentina', 'الأرجنتين', 'AR', 'ARG', '+54'),
('Armenia', 'أرمينيا', 'AM', 'ARM', '+374'),
('Australia', 'أستراليا', 'AU', 'AUS', '+61'),
('Austria', 'النمسا', 'AT', 'AUT', '+43'),
('Azerbaijan', 'أذربيجان', 'AZ', 'AZE', '+994'),
('Bahamas', 'الباهاما', 'BS', 'BHS', '+1-242'),
('Bahrain', 'البحرين', 'BH', 'BHR', '+973'),
('Bangladesh', 'بنغلاديش', 'BD', 'BGD', '+880'),
('Barbados', 'بربادوس', 'BB', 'BRB', '+1-246'),
('Belarus', 'بيلاروسيا', 'BY', 'BLR', '+375'),
('Belgium', 'بلجيكا', 'BE', 'BEL', '+32'),
('Belize', 'بليز', 'BZ', 'BLZ', '+501'),
('Benin', 'بنين', 'BJ', 'BEN', '+229'),
('Bhutan', 'بوتان', 'BT', 'BTN', '+975'),
('Bolivia', 'بوليفيا', 'BO', 'BOL', '+591'),
('Bosnia and Herzegovina', 'البوسنة والهرسك', 'BA', 'BIH', '+387'),
('Botswana', 'بوتسوانا', 'BW', 'BWA', '+267'),
('Brazil', 'البرازيل', 'BR', 'BRA', '+55'),
('Brunei', 'بروناي', 'BN', 'BRN', '+673'),
('Bulgaria', 'بلغاريا', 'BG', 'BGR', '+359'),
('Burkina Faso', 'بوركينا فاسو', 'BF', 'BFA', '+226'),
('Burundi', 'بوروندي', 'BI', 'BDI', '+257'),
('Cabo Verde', 'الرأس الأخضر', 'CV', 'CPV', '+238'),
('Cambodia', 'كمبوديا', 'KH', 'KHM', '+855'),
('Cameroon', 'الكاميرون', 'CM', 'CMR', '+237'),
('Canada', 'كندا', 'CA', 'CAN', '+1'),
('Central African Republic', 'جمهورية أفريقيا الوسطى', 'CF', 'CAF', '+236'),
('Chad', 'تشاد', 'TD', 'TCD', '+235'),
('Chile', 'تشيلي', 'CL', 'CHL', '+56'),
('China', 'الصين', 'CN', 'CHN', '+86'),
('Colombia', 'كولومبيا', 'CO', 'COL', '+57'),
('Comoros', 'جزر القمر', 'KM', 'COM', '+269'),
('Congo (Congo-Brazzaville)', 'الكونغو', 'CG', 'COG', '+242'),
('Costa Rica', 'كوستاريكا', 'CR', 'CRI', '+506'),
('Croatia', 'كرواتيا', 'HR', 'HRV', '+385'),
('Cuba', 'كوبا', 'CU', 'CUB', '+53'),
('Cyprus', 'قبرص', 'CY', 'CYP', '+357'),
('Czechia (Czech Republic)', 'التشيك', 'CZ', 'CZE', '+420'),
('Democratic Republic of the Congo', 'جمهورية الكونغو الديمقراطية', 'CD', 'COD', '+243'),
('Denmark', 'الدنمارك', 'DK', 'DNK', '+45'),
('Djibouti', 'جيبوتي', 'DJ', 'DJI', '+253'),
('Dominica', 'دومينيكا', 'DM', 'DMA', '+1-767'),
('Dominican Republic', 'جمهورية الدومينيكان', 'DO', 'DOM', '+1-809'),
('Ecuador', 'الإكوادور', 'EC', 'ECU', '+593'),
('Egypt', 'مصر', 'EG', 'EGY', '+20'),
('El Salvador', 'السلفادور', 'SV', 'SLV', '+503'),
('Equatorial Guinea', 'غينيا الاستوائية', 'GQ', 'GNQ', '+240'),
('Eritrea', 'إريتريا', 'ER', 'ERI', '+291'),
('Estonia', 'إستونيا', 'EE', 'EST', '+372'),
('Eswatini (fmr. "Swaziland")', 'إسواتيني', 'SZ', 'SWZ', '+268'),
('Ethiopia', 'إثيوبيا', 'ET', 'ETH', '+251'),
('Fiji', 'فيجي', 'FJ', 'FJI', '+679'),
('Finland', 'فنلندا', 'FI', 'FIN', '+358'),
('France', 'فرنسا', 'FR', 'FRA', '+33'),
('Gabon', 'الغابون', 'GA', 'GAB', '+241'),
('Gambia', 'غامبيا', 'GM', 'GMB', '+220'),
('Georgia', 'جورجيا', 'GE', 'GEO', '+995'),
('Germany', 'ألمانيا', 'DE', 'DEU', '+49'),
('Ghana', 'غانا', 'GH', 'GHA', '+233'),
('Greece', 'اليونان', 'GR', 'GRC', '+30'),
('Grenada', 'غرينادا', 'GD', 'GRD', '+1-473'),
('Guatemala', 'غواتيمالا', 'GT', 'GTM', '+502'),
('Guinea', 'غينيا', 'GN', 'GIN', '+224'),
('Guinea-Bissau', 'غينيا بيساو', 'GW', 'GNB', '+245'),
('Guyana', 'غيانا', 'GY', 'GUY', '+592'),
('Haiti', 'هايتي', 'HT', 'HTI', '+509'),
('Honduras', 'هندوراس', 'HN', 'HND', '+504'),
('Hungary', 'المجر', 'HU', 'HUN', '+36'),
('Iceland', 'آيسلندا', 'IS', 'ISL', '+354'),
('India', 'الهند', 'IN', 'IND', '+91'),
('Indonesia', 'إندونيسيا', 'ID', 'IDN', '+62'),
('Iran', 'إيران', 'IR', 'IRN', '+98'),
('Iraq', 'العراق', 'IQ', 'IRQ', '+964'),
('Ireland', 'أيرلندا', 'IE', 'IRL', '+353'),
('Israel', 'إسرائيل', 'IL', 'ISR', '+972'),
('Italy', 'إيطاليا', 'IT', 'ITA', '+39'),
('Jamaica', 'جامايكا', 'JM', 'JAM', '+1-876'),
('Japan', 'اليابان', 'JP', 'JPN', '+81'),
('Jordan', 'الأردن', 'JO', 'JOR', '+962'),
('Kazakhstan', 'كازاخستان', 'KZ', 'KAZ', '+7'),
('Kenya', 'كينيا', 'KE', 'KEN', '+254'),
('Kiribati', 'كيريباتي', 'KI', 'KIR', '+686'),
('Kuwait', 'الكويت', 'KW', 'KWT', '+965'),
('Kyrgyzstan', 'قيرغيزستان', 'KG', 'KGZ', '+996'),
('Laos', 'لاوس', 'LA', 'LAO', '+856'),
('Latvia', 'لاتفيا', 'LV', 'LVA', '+371'),
('Lebanon', 'لبنان', 'LB', 'LBN', '+961'),
('Lesotho', 'ليسوتو', 'LS', 'LSO', '+266'),
('Liberia', 'ليبيريا', 'LR', 'LBR', '+231'),
('Libya', 'ليبيا', 'LY', 'LBY', '+218'),
('Liechtenstein', 'ليختنشتاين', 'LI', 'LIE', '+423'),
('Lithuania', 'ليتوانيا', 'LT', 'LTU', '+370'),
('Luxembourg', 'لوكسمبورغ', 'LU', 'LUX', '+352'),
('Madagascar', 'مدغشقر', 'MG', 'MDG', '+261'),
('Malawi', 'مالاوي', 'MW', 'MWI', '+265'),
('Malaysia', 'ماليزيا', 'MY', 'MYS', '+60'),
('Maldives', 'المالديف', 'MV', 'MDV', '+960'),
('Mali', 'مالي', 'ML', 'MLI', '+223'),
('Malta', 'مالطا', 'MT', 'MLT', '+356'),
('Marshall Islands', 'جزر مارشال', 'MH', 'MHL', '+692'),
('Mauritania', 'موريتانيا', 'MR', 'MRT', '+222'),
('Mauritius', 'موريشيوس', 'MU', 'MUS', '+230'),
('Mexico', 'المكسيك', 'MX', 'MEX', '+52'),
('Micronesia', 'ميكرونيزيا', 'FM', 'FSM', '+691'),
('Moldova', 'مولدوفا', 'MD', 'MDA', '+373'),
('Monaco', 'موناكو', 'MC', 'MCO', '+377'),
('Mongolia', 'منغوليا', 'MN', 'MNG', '+976'),
('Montenegro', 'الجبل الأسود', 'ME', 'MNE', '+382'),
('Morocco', 'المغرب', 'MA', 'MAR', '+212'),
('Mozambique', 'موزمبيق', 'MZ', 'MOZ', '+258'),
('Myanmar (formerly Burma)', 'ميانمار', 'MM', 'MMR', '+95'),
('Namibia', 'ناميبيا', 'NA', 'NAM', '+264'),
('Nauru', 'ناورو', 'NR', 'NRU', '+674'),
('Nepal', 'نيبال', 'NP', 'NPL', '+977'),
('Netherlands', 'هولندا', 'NL', 'NLD', '+31'),
('New Zealand', 'نيوزيلندا', 'NZ', 'NZL', '+64'),
('Nicaragua', 'نيكاراغوا', 'NI', 'NIC', '+505'),
('Niger', 'النيجر', 'NE', 'NER', '+227'),
('Nigeria', 'نيجيريا', 'NG', 'NGA', '+234'),
('North Korea', 'كوريا الشمالية', 'KP', 'PRK', '+850'),
('North Macedonia', 'مقدونيا الشمالية', 'MK', 'MKD', '+389'),
('Norway', 'النرويج', 'NO', 'NOR', '+47'),
('Oman', 'عمان', 'OM', 'OMN', '+968'),
('Pakistan', 'باكستان', 'PK', 'PAK', '+92'),
('Palau', 'بالاو', 'PW', 'PLW', '+680'),
('Palestine State', 'فلسطين', 'PS', 'PSE', '+970'),
('Panama', 'بنما', 'PA', 'PAN', '+507'),
('Papua New Guinea', 'بابوا غينيا الجديدة', 'PG', 'PNG', '+675'),
('Paraguay', 'باراغواي', 'PY', 'PRY', '+595'),
('Peru', 'بيرو', 'PE', 'PER', '+51'),
('Philippines', 'الفلبين', 'PH', 'PHL', '+63'),
('Poland', 'بولندا', 'PL', 'POL', '+48'),
('Portugal', 'البرتغال', 'PT', 'PRT', '+351'),
('Qatar', 'قطر', 'QA', 'QAT', '+974'),
('Romania', 'رومانيا', 'RO', 'ROU', '+40'),
('Russia', 'روسيا', 'RU', 'RUS', '+7'),
('Rwanda', 'رواندا', 'RW', 'RWA', '+250'),
('Saint Kitts and Nevis', 'سانت كيتس ونيفيس', 'KN', 'KNA', '+1-869'),
('Saint Lucia', 'سانت لوسيا', 'LC', 'LCA', '+1-758'),
('Saint Vincent and the Grenadines', 'سانت فنسنت وجزر غرينادين', 'VC', 'VCT', '+1-784'),
('Samoa', 'ساموا', 'WS', 'WSM', '+685'),
('San Marino', 'سان مارينو', 'SM', 'SMR', '+378'),
('Sao Tome and Principe', 'ساو تومي وبرينسيبي', 'ST', 'STP', '+239'),
('Saudi Arabia', 'المملكة العربية السعودية', 'SA', 'SAU', '+966'),
('Senegal', 'السنغال', 'SN', 'SEN', '+221'),
('Serbia', 'صربيا', 'RS', 'SRB', '+381'),
('Seychelles', 'سيشيل', 'SC', 'SYC', '+248'),
('Sierra Leone', 'سيراليون', 'SL', 'SLE', '+232'),
('Singapore', 'سنغافورة', 'SG', 'SGP', '+65'),
('Slovakia', 'سلوفاكيا', 'SK', 'SVK', '+421'),
('Slovenia', 'سلوفينيا', 'SI', 'SVN', '+386'),
('Solomon Islands', 'جزر سليمان', 'SB', 'SLB', '+677'),
('Somalia', 'الصومال', 'SO', 'SOM', '+252'),
('South Africa', 'جنوب أفريقيا', 'ZA', 'ZAF', '+27'),
('South Korea', 'كوريا الجنوبية', 'KR', 'KOR', '+82'),
('South Sudan', 'جنوب السودان', 'SS', 'SSD', '+211'),
('Spain', 'إسبانيا', 'ES', 'ESP', '+34'),
('Sri Lanka', 'سريلانكا', 'LK', 'LKA', '+94'),
('Sudan', 'السودان', 'SD', 'SDN', '+249'),
('Suriname', 'سورينام', 'SR', 'SUR', '+597'),
('Sweden', 'السويد', 'SE', 'SWE', '+46'),
('Switzerland', 'سويسرا', 'CH', 'CHE', '+41'),
('Syria', 'سوريا', 'SY', 'SYR', '+963'),
('Tajikistan', 'طاجيكستان', 'TJ', 'TJK', '+992'),
('Tanzania', 'تنزانيا', 'TZ', 'TZA', '+255'),
('Thailand', 'تايلاند', 'TH', 'THA', '+66'),
('Timor-Leste', 'تيمور الشرقية', 'TL', 'TLS', '+670'),
('Togo', 'توغو', 'TG', 'TGO', '+228'),
('Tonga', 'تونغا', 'TO', 'TON', '+676'),
('Trinidad and Tobago', 'ترينيداد وتوباغو', 'TT', 'TTO', '+1-868'),
('Tunisia', 'تونس', 'TN', 'TUN', '+216'),
('Turkey', 'تركيا', 'TR', 'TUR', '+90'),
('Turkmenistan', 'تركمانستان', 'TM', 'TKM', '+993'),
('Tuvalu', 'توفالو', 'TV', 'TUV', '+688'),
('Uganda', 'أوغندا', 'UG', 'UGA', '+256'),
('Ukraine', 'أوكرانيا', 'UA', 'UKR', '+380'),
('United Arab Emirates', 'الإمارات العربية المتحدة', 'AE', 'ARE', '+971'),
('United Kingdom', 'المملكة المتحدة', 'GB', 'GBR', '+44'),
('United States of America', 'الولايات المتحدة الأمريكية', 'US', 'USA', '+1'),
('Uruguay', 'أوروغواي', 'UY', 'URY', '+598'),
('Uzbekistan', 'أوزبكستان', 'UZ', 'UZB', '+998'),
('Vanuatu', 'فانواتو', 'VU', 'VUT', '+678'),
('Vatican City', 'مدينة الفاتيكان', 'VA', 'VAT', '+379'),
('Venezuela', 'فنزويلا', 'VE', 'VEN', '+58'),
('Vietnam', 'فيتنام', 'VN', 'VNM', '+84'),
('Yemen', 'اليمن', 'YE', 'YEM', '+967'),
('Zambia', 'زامبيا', 'ZM', 'ZMB', '+260'),
('Zimbabwe', 'زيمبابوي', 'ZW', 'ZWE', '+263');

*/